# Generated by Django 4.2.9 on 2024-01-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neo4j_manage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="family_name",
            field=models.CharField(default="na", max_length=255),
            preserve_default=False,
        ),
    ]
