# Generated by Django 4.2.10 on 2024-04-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neo4j_manage", "0002_crop_family_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="is_synced",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")], default="N", max_length=1
            ),
        ),
    ]
