# Generated by Django 4.2.9 on 2024-01-13 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Crop",
        ),
    ]
