# Generated by Django 4.2.9 on 2024-01-13 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_delete_crop"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QueryHistory",
        ),
    ]
