# Generated by Django 4.2.10 on 2024-04-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query", "0002_queryhistory_ans_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryhistory",
            name="ans_status",
            field=models.CharField(
                choices=[
                    ("KG", "Knowledge Graph"),
                    ("LLM", "Large Language Model"),
                    ("F", "Failed"),
                    ("E", "Exception"),
                ],
                default="F",
                max_length=3,
            ),
        ),
    ]
